package warehouse.frontend;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class AccountVerification extends javax.swing.JFrame {

    private String email;
    private String username;
    private String userphone;
    private String userrole;

    /**
     * Creates new form AccountVerification
     */
    public AccountVerification(String email) {
        initComponents();
        this.email = email;
        setupOTPFields();//Call the method to setup OTP fields
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Check if the window is maximized
                if ((getExtendedState() & MAXIMIZED_BOTH) == MAXIMIZED_BOTH) {
                    // Set background color of JFrame when maximized
                    getContentPane().setBackground(new Color(0, 51, 51));
                    // Center jPanel1
                    Container.setLocation((getWidth() - Container.getWidth()) / 2,
                            (getHeight() - Container.getHeight()) / 2);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Value1 = new javax.swing.JTextField();
        Value2 = new javax.swing.JTextField();
        Value3 = new javax.swing.JTextField();
        Value4 = new javax.swing.JTextField();
        VerifyBtn = new javax.swing.JButton();
        ResendOTPbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Container\n");
        setPreferredSize(new java.awt.Dimension(600, 500));

        Container.setBackground(new java.awt.Color(0, 102, 102));
        Container.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ACCOUNT VERIFICATION PAGE");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("<html>\n<p>Please Enter OTP Verification Code Sent To example@gmail.com</p>\n</html>");

        Value1.setPreferredSize(new java.awt.Dimension(40, 20));

        Value2.setPreferredSize(new java.awt.Dimension(40, 20));

        Value3.setPreferredSize(new java.awt.Dimension(40, 20));

        Value4.setPreferredSize(new java.awt.Dimension(40, 20));
        Value4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Value4ActionPerformed(evt);
            }
        });

        VerifyBtn.setBackground(new java.awt.Color(0, 102, 102));
        VerifyBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        VerifyBtn.setForeground(new java.awt.Color(242, 242, 242));
        VerifyBtn.setText("FINISH");
        VerifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionperformed(evt);
            }
        });

        ResendOTPbtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ResendOTPbtn.setForeground(new java.awt.Color(204, 0, 0));
        ResendOTPbtn.setLabel("RESEND");
        ResendOTPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResendOTPbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Didn't Receive Code?\n");

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ContainerLayout.createSequentialGroup()
                                .addComponent(Value1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Value2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Value3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Value4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VerifyBtn)))
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResendOTPbtn)
                            .addComponent(jLabel3))
                        .addGap(204, 204, 204)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Value4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(Value1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Value2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Value3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(VerifyBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ResendOTPbtn)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 692, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Value4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Value4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Value4ActionPerformed

    private void actionperformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionperformed
        //Predefined OTP for testing (in real case,retrieve this from your OTP generation logic)
        String predefinedOTP = "1234";
        //Concatenate the entered OTP from 4 text fields
        String enteredOTP = Value1.getText() + Value2.getText() + Value3.getText() + Value4.getText();
        if (enteredOTP.equals(predefinedOTP)) {
            JOptionPane.showMessageDialog(this, "OTP Verified Successfully!");
            CreatePassword createpasswordFrame = new CreatePassword(email, username, userphone, userrole);
            createpasswordFrame.setVisible(true);
            createpasswordFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_actionperformed

    private void ResendOTPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResendOTPbtnActionPerformed
        // TODO add your handling code here:
    }

    private void setupOTPFields() {
        JTextField[] otpFields = {Value1, Value2, Value3, Value4};
        for (int i = 0; i < otpFields.length; i++) {
            int currentIndex = i;
            otpFields[i].addKeyListener(new KeyAdapter() {
                @Override
                public void keyPressed(KeyEvent e) {
                    if (e.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
                        if (otpFields[currentIndex].getText().isEmpty() && currentIndex > 0) {
                            otpFields[currentIndex - 1].requestFocus();
                        }
                    }
                }
            });
            otpFields[i].addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    otpFields[currentIndex].selectAll();
                }
            });
            otpFields[i].addCaretListener(e -> {
                if (otpFields[currentIndex].getText().length() == 1) {
                    if (currentIndex < otpFields.length - 1) {
                        otpFields[currentIndex + 1].requestFocus();
                    }
                }
            });
        }
    }

    private void highlightInvalidFields() {
        JTextField[] otpFields = {Value1, Value2, Value3, Value4};
        for (JTextField field : otpFields) {
            field.setBorder(BorderFactory.createLineBorder(Color.RED));//Set border color to red

        }
    }//GEN-LAST:event_ResendOTPbtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton ResendOTPbtn;
    private javax.swing.JTextField Value1;
    private javax.swing.JTextField Value2;
    private javax.swing.JTextField Value3;
    private javax.swing.JTextField Value4;
    private javax.swing.JButton VerifyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
